# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Laura CI

on:
  push:
    branches: [ lauradev, laura2 ]
  pull_request:
    branches: [ lauradev, laura2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkstyle
      run: mvn -B checkstyle:check --file laura/portfolio/pom.xml
    - name: Build
      run: mvn -B package --file laura/portfolio/pom.xml
    - name: Test
      run: mvn -B test --file laura/portfolio/pom.xml
